name: porsche_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.15+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_analytics: ^5.0.15
  firebase_messaging: ^6.0.16

  mask_text_input_formatter: ^1.0.7

  video_player: ^0.10.11+2
  audioplayers: ^0.15.1

  flutter_slidable: ^0.5.4
  scroll_to_index: ^1.0.6

  image_picker: ^0.6.7+3
  image_cropper: ^1.2.3


  auto_route: ^0.5.0
  injectable: 0.4.0
  get_it: ^4.0.2
  supercharged: ^1.6.0
  provider: ^4.0.4
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  shared_preferences: ^0.5.7+3


  freezed_annotation:
  json_annotation: ^3.0.0

  dio: ^3.0.9
  retrofit: ^1.3.4

  intl: ^0.16.1
  simple_animations: ^2.2.1
  cupertino_icons: ^0.1.3

  logger: ^0.7.0
  logger_flutter: ^0.7.1
  shake: ^0.1.0

  firebase_crashlytics: ^0.1.3+3

  expandable: ^4.1.4
  time_formatter: ^1.0.0
  package_info: ^0.4.1
  url_launcher: ^5.5.0

  google_maps_webservice: ^0.0.17

  flutter_webview_plugin: ^0.3.11

  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0

  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1
  build_runner:
  mobx_codegen: ^1.1.0
  freezed:
  json_serializable: ^3.2.0
  retrofit_generator: ^1.3.7


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cars/
    - assets/images/cars/porsche-panamera-4s/
    - assets/images/cars/porsche-cayenne-coupe-s/
    - assets/images/cars/porsche-718-boxter-s/
    - assets/images/cars/porsche-911-carrera-s/
    - assets/images/cars/porsche-cayenne-s/

  fonts:
    - family: PorscheNext
      fonts:
        - asset: assets/fonts/porscheNext/PorscheNext-Regular.ttf
        - asset: assets/fonts/porscheNext/PorscheNext-Thin.ttf
          weight: 100
        - asset: assets/fonts/porscheNext/PorscheNext-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/porscheNext/PorscheNext-Bold.ttf
          weight: 700

    - family: PorscheIcons
      fonts:
        - asset: assets/fonts/porscheIcons/PorscheIcons.ttf

flutter_intl:
  enabled: true
  main_locale: ru
